version: 0.2

phases:
  install:
    commands:
      - echo Install phase started
  pre_build:
    commands:
      - echo Started pre_build phase
      - ls -al
      - python --version
      - aws --version
      - aws s3 cp --recursive ./scripts/ s3://glue-script-path-dma/scripts/
  build:
    commands:
      - echo Build started on 'date'
      - aws cloudformation deploy --template-file glue.yml --stack-name GlueJobsDMA --parameter-overrides file://parameters.json
