AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  GlueRole:
    Type: String
    Description: ARN da role do Glue
    Default: arn:aws:iam::850202893763:role/RoleProducerDMA
  GlueScriptsS3:
    Type: String
    Description: Bucket do S3 onde os scripts Glue estão localizados
    Default: glue-script-path-dma
  TagDMA:
    Type: String
    Description: Tag DMA
    Default: DataMeshAcademy

Resources:
  ProdutoCreditoSorJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "corp_produto_cartao_credito_sor"
      Role: !Sub "${GlueRole}"
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${GlueScriptsS3}/src/script_sor.py"
        PythonVersion: "3"
      NumberOfWorkers: 2
      WorkerType: G.1X
      Timeout: 45
      GlueVersion: '4.0'
      ExecutionProperty:
        MaxConcurrentRuns: 2
      SecurityConfiguration: "glue_security_configuration"
      Tags:
        DMA: !Ref TagDMA
      Arguments:
        --enable-glue-datacatalog: 'true'
        --enable-spark-ui: 'true'

  ProdutoCreditoSotJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "corp_produto_cartao_credito_sot"
      Role: !Sub "${GlueRole}"
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${GlueScriptsS3}/src/script_sot.py"
        PythonVersion: "3"
      NumberOfWorkers: 2
      WorkerType: G.1X
      Timeout: 45
      GlueVersion: '4.0'
      ExecutionProperty:
        MaxConcurrentRuns: 2
      SecurityConfiguration: "glue_security_configuration"
      Tags:
        DMA: !Ref TagDMA
      Arguments:
        --enable-glue-datacatalog: 'true'
        --enable-spark-ui: 'true'

  ProdutoCreditoSpecJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "corp_produto_cartao_credito_spec"
      Role: !Sub "${GlueRole}"
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${GlueScriptsS3}/src/script_spec.py"
        PythonVersion: "3"
      NumberOfWorkers: 2
      WorkerType: G.1X
      Timeout: 45
      GlueVersion: '4.0'
      ExecutionProperty:
        MaxConcurrentRuns: 2
      SecurityConfiguration: "glue_security_configuration"
      Tags:
        DMA: !Ref TagDMA
      Arguments:
        --enable-glue-datacatalog: 'true'
        --enable-spark-ui: 'true'
